### ISSUE TITLE
Groovy: eventBus.send() with DeliveryOptions fails in 3.6.3

### ISSUE THREAD

**Issue by injecteer** [vert-x3/issues-and-wiki#32]
my Groovy code:

```
class GatewayVerticle extends AbstractVerticle {
  DeliveryOptions HOP_OPTS = new DeliveryOptions( sendTimeout:5000 )
  @Override
  void start() throws Exception {    
    vertx.eventBus().send( 'addr', [ aa:42 ], HOP_OPTS ){ println it }
  }
}

```
fails with

>  java.lang.IllegalArgumentException: No message codec for type: class java.util.LinkedHashMap at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101) at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.createMessage(ClusteredEventBus.java:180) at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:111)

If I ommit the setting sendTimeout it fails with the same exception.

The following line works just fine:
`
vertx.eventBus().send( 'gateway', [ aa:42 ] ){ doSomeStuff() }`

If I convert the map into JsonObject, it also works:
`
vertx.eventBus().send( 'addr', new JsonObject( aa:42 ), HOP_OPTS ){}`

See https://stackoverflow.com/questions/55415485/vertx-3-6-3-eventbus-send-with-deliveryoptions-fail for further discuccsion

**Comment by injecteer** [comment]
proper one https://github.com/vert-x3/vertx-lang-groovy/issues/75
